version: '2.2'

services:
  python:
    build:
      context: . # donde esta el dockerfile
      dockerfile: Dockerfile
    container_name: mi-python
    tty: true # -it interactively
    ipc: host
     #image: mysql:5.7
    volumes:
      - ../app:/app
    
     #restart: always
    # ports:
    #   - 8787:8787
    # environment:
    #   DISABLE_AUTH: true 
    #   ROOT: true
    #   PASSWORD: 123      
 
  #   container_name: NodeForMysql
  #   build: .
volumes:
  app: 
    external: true
  