FROM tensorflow/tensorflow:2.14.0-gpu

RUN pip install ipykernel

# tensorflow-probability==0.22.1 xq no tengo la tf version = 2.15
RUN pip install tensorflow-probability==0.22.1
RUN pip install matplotlib
RUN pip install scikit-learn
RUN pip install pandas
RUN pip install tensorflow-hub
#RUN pip install pydot