version: '2.2'

services:
  tensorflow:
    build:
      context: . # donde esta el dockerfile
      dockerfile: Dockerfile
    container_name: mi-tensorflow
    tty: true # -it interactively
    ipc: host
     #image: mysql:5.7
    # stdin_open: true
    # cpus: 0.5
    volumes:
      - ../app:/app
      - ../../pytorch/app/pytorch_cv_projects/dataset:/app/dataset
    
               
    network_mode: host # Dar internet
    # environment:
    #   - DISPLAY=$DISPLAY
    #   - XSOCK=/tmp/.X11-unix
    #   - XAUTH=/tmp/.docker.xauth
    # extra_hosts:
    #   - "video:192.168.1.7"

    #restart: always
    # ports:
    #   - 8787:8787
    # environment:
    #   DISABLE_AUTH: true 
    #   ROOT: true
    #   PASSWORD: 123      
    #GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  
  #  node:
  #   container_name: NodeForMysql
  #   build: .
volumes:
  app: 
    external: true

  