version: '3'

services:
  flask:
    labels:
      shipyard.route: '/'
    build:
      context: . # donde esta el dockerfile
      dockerfile: Dockerfile
    container_name: mi-flask
    ports:
     - 5000:5000
    tty: true # -it interactively
    ipc: host
    environment:
      - FLASK_APP=app 
    working_dir: /srv
    volumes:
      - ../srv:/srv
    depends_on:
      - requirements
    command: ["python","app.py"]

  requirements:
    build:
      context: . # donde esta el dockerfile
      dockerfile: Dockerfile




volumes:
  srv: 
    external: true