version: '2.2'

services:
  whisper:
    build:
      context: . # donde esta el dockerfile
      dockerfile: Dockerfile
    container_name: mi-whisper
    tty: true # -it interactively
    # ipc: host
     #image: mysql:5.7
    volumes:
      - ../app:/app
    
     #restart: always
    # ports:
    #   - 9000:9000
    # # environment:
    #   ASR_MODEL: large  # model
    #   ASR_ENGINE: openai_whisper # o "faster_whisper"
    #GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  
  #  node:
  #   container_name: NodeForMysql
  #   build: .
volumes:
  app: 
    external: true
  